package esri;

import js.Dom;
/* <i>Class added v2.5</i><br/><pre class='prettyprint'>dojo.require("esri.IdentityManagerBase");</pre>The
        Credential class represents a credential object used to access a secure
        ArcGIS resource.*/
@native ("esri.Credential")
extern class Credential {
	/* Token expiration time specified as number of milliseconds since 1 January
            1970 00:00:00 UTC.*/
	public var expires:String;
	/* The server url.*/
	public var server:String;
	/* Token generated by the token service using the specified userId and password.*/
	public var token:String;
	/* User associated wth the <code>Credential</code> object.*/
	public var userId:String;


	/* <p>Generate a new token and update the Credential's token property
            with the newly acquired token. Tokens are typically kept valid using a
            timer that automatically triggers a refresh before the token expires. Use
            this method in cases where the timer has been delayed or stopped. </p>*/
	public function refreshToken():Dynamic;
}